/**
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is merely a loader for the infinitymint.config.js and you should put inside of the hardhat key what ever you would
 * put inside of here.
 */

//them aliases
require("module-alias/register");
//import our hardhat plugins
require("@nomicfoundation/hardhat-toolbox");
require("@nomiclabs/hardhat-ethers");
require( "hardhat-deploy");
require( "hardhat-change-network"); //allows hre.changeNetwork to occur

//imports
let {
  prepareConfig,
  loadInfinityMint,
  logDirect,
} = require("infinitymint/dist/app/helpers");
let { createDefaultFactory } = require("infinitymint/dist/app/pipes");

//create default pipe
createDefaultFactory();

//require dotenv
require("dotenv").config({
  override: false, //will not override already established environment variables
});

//load infinitymint and create default files
loadInfinityMint(true, false);

//return the infinitymint config file
let config = prepareConfig();
logDirect("🧱 Loaded hardhat.config.js");
modoule.exports = config.hardhat; //export the infinity mint configuration file
